TFFP = "{tffp: " MESSAGE "}"

MESSAGE = CLIENT_REQUEST / SERVER_RESPONSE / SERVER_UPDATE

CLIENT_REQUEST = "{type: 'seek', body: {" LOCATION ", " NEW_POST_REQUEST / POST_CONTENT_REQUEST / JOIN_GROUP_REQUEST / GROUP_MEMBERS_REQUEST "}}"
NEW_POST_REQUEST = "command: 'post', args: {subject: " STRING ", content: " STRING "}"
POST_CONTENT_REQUEST = "command: 'content', args: " POST_ID ""
JOIN_GROUP_REQUEST = "command: 'join'"
GROUP_MEMBERS_REQUEST = "command: 'users'"

SERVER_RESPONSE = ACCEPT / DENY
ACCEPT = "{type: 'good', body: " RESPONSE_TEXT "}"
DENY = "{type: 'moot', body: " RESPONSE_TEXT "}"
RESPONSE_TEXT = STRING

SERVER_UPDATE = "{type: 'hoot', body: {" LOCATION ", " NEW_POST_UPDATE / GROUP_UPDATE "}}"
NEW_POST_UPDATE = "update: 'post', data: {id: " POST_ID ", sender: " USER_ID ", date: " DATE " subject: "STRING"}"
GROUP_UPDATE = "update: 'users', data: " USER_ID_LIST

LOCATION = "group: " GROUP_ID

POST_ID = INT
USER_ID = STRING
GROUP_ID = "public" / PRIVATE
PRIVATE = STRING
DATE = STRING
